# fly.toml app configuration file generated for trailwright-api on 2025-08-18T23:34:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'trailwright-api'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  ENVIRONMENT = 'production'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
